### PR TITLE
Add Docker build option

### PR DESCRIPTION
**Pull request by fhemberger**
Removes the macOS build option in favor of a Docker build. This also eliminates
the need to provide the `isohdpfx.bin` in the repository, which might have been
a security concern.

The Docker image uses fixed paths for required input and output instead of
accepting parameters. The flexibility of the underlying script is preserved
through mounting different paths during `docker run`.

Fixes: #13

### CODE REVIEW

**Comment by fhemberger** [comment]
@core-process Second attempt. ;)

The build command boils now down to `docker run <mount ssh public key> <mount output> ubuntu-unattended <version|18.04>`. See readme for details.

**Comment by fhemberger** [comment]
@core-process What do you think?

**Comment by core-process** [comment]
@fhemberger Sorry for the late response. I like it very much. The only reason I am hesitating is that I would prefer to keep the MacOS compatibility. Still, I agree with your concern regarding the binary. I am thinking about a download and extraction procedure which will be used as a fallback in case the `isohdpfx.bin` is not available locally. I will merge your PR within the next days, once I completed my addition.

**Comment by dentarg** [comment]
> This also eliminates the need to provide the `isohdpfx.bin` in the repository, which might have been a security concern.

I really like this 👍 

Tried out this branch, and once I updated `build-iso.sh` to use `"/usr/lib/ISOLINUX/isohdpfx.bin"` it worked flawlessly, thanks!

**Comment by fhemberger** [comment]
@core-process I updated the PR to restore the original Mac build option.
Can we get this merged now?

**Comment by hadrien-toma** [comment]
@fhemberger Excellent contribution, thank you very much :pray:!
@dentarg Thank you for pointing me there, you were totally right, having this branch merged will fixed #24 :yum: 
@core-process any news about this merge? :worried:

**Pull request merged**
